//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public Nullable<int> DrinkID { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> StockQuantity { get; set; }
    
        public virtual Drink Drink { get; set; }
    }
}
