//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        public string StaffSDT { get; set; }
        public string StaffName { get; set; }
        public string StaffEmail { get; set; }
        public decimal Coefficient { get; set; }
        public int Worktime { get; set; }
    }
}
