//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int StatisticID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<decimal> TotalBookings { get; set; }
        public Nullable<decimal> TotalDrinksSold { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> TotalBookedPitch { get; set; }
    }
}
